// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AvatarUpdateController from "./avatar_update_controller"
application.register("avatar-update", AvatarUpdateController)

import CommentsController from "./comments_controller"
application.register("comments", CommentsController)

import FollowController from "./follow_controller"
application.register("follow", FollowController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)
